Section "InputClass"
	Identifer "toucjpad"
	MatchIsTouchpad "on"
	Driver "libinput"
	Option "Tapping" "on"
	Option "NaturalScrolling" "true"
	Option "ScrollMethod" "twofinger"
	Option "DisableWhileTyping" "true"
EndSection
