#!/usr/bin/sh

#AUTOSTART
sxhkd &
xsetroot -cursor_name left_ptr &
picom &

# kb layout
setxkbmap -layout "us, ru" -option "grp:alt_shift_toggle"

#colors by pywal
source ~/.cache/wal/colors.sh

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap          10

# COLORS
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

bspc config presel_feedback_color "$color1"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# focus on window by cursor
bspc config focus_follows_pointer true
bspc config pointer_modifier super

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# for wallpaper save
if [ -f "$HOME/.fehbg" ]; then
	bash "$HOME/.fehbg"
fi

xrdb -merge ~/.cache/wal/colors.Xresources

# start polybar
polybar &
